# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FindingPluto' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FindingPluto

  pod 'RxSwift'
  pod 'RxCocoa'

  target 'FindingPlutoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FindingPlutoUITests' do
    # Pods for testing
  end

end
